---
permalink: install-linux/task_selinux_requirements_for_mounting_opt_netapp.html 
sidebar: sidebar 
keywords: unified manager, selinux requirements, mounting, nfs, cifs, share 
summary: NAS 또는 SAN 장치에 /opt/NetApp 또는 /opt/NetApp/데이터를 마운트하고 SELinux를 사용하도록 설정한 경우 다음 사항을 고려해야 합니다. 
---
= NFS 및 CIFS 공유에 대한 SELinux 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
을(를) 탑재하려는 경우 `/opt/netapp` 또는 `/opt/netapp/data` NAS 또는 SAN 디바이스에서 SELinux를 설정한 경우 몇 가지 고려 사항을 염두에 두어야 합니다.

을(를) 탑재하려는 경우 `/opt/netapp` 또는 `/opt/netapp/data` 루트 파일 시스템 이외의 모든 환경에서 SELinux를 설정한 경우 마운트된 디렉토리에 대한 올바른 컨텍스트를 설정해야 합니다.
사용자 환경의 해당 시나리오에 대해 올바른 SELinux 컨텍스트를 설정하고 확인하려면 다음 단계를 수행하십시오.



== SELinux 컨텍스트 구성 시기 `/opt/netapp/data` 탑재됩니다

을(를) 장착한 경우 `/opt/netapp/data` 시스템과 SELinux가 로 설정되어 있습니다 `Enforcing`에 대한 SELinux 컨텍스트 유형이 있는지 확인합니다 `/opt/netapp/data` 가 로 설정되어 있습니다 `mysqld_db_t`데이터베이스 파일 위치에 대한 기본 컨텍스트 요소입니다.

. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
`ls -dZ /opt/netapp/data`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp/data
----
+

NOTE: 이 출력에서 컨텍스트는 입니다 `default_t`. 이 컨텍스트를 로 변경해야 합니다 `mysqld_db_t`.

. 다음 단계를 수행하여 마운트한 방법에 따라 컨텍스트를 설정합니다 `/opt/netapp/data`.
+
.. 다음 명령을 실행하여 컨텍스트를 로 설정합니다 `mysqld_db_t`:
`semanage fcontext -a -t mysqld_db_t "/opt/netapp/data"
`restorecon -R -v /opt/netapp/data`
.. 을(를) 구성한 경우 `/opt/netapp/data` 인치 `/etc/fstab`을 편집해야 합니다 `/etc/fstab` 파일. 의 경우 `/opt/netapp/data/` 마운트 옵션을 선택하고 MySQL 레이블을 다음과 같이 추가합니다.
+
`context=system_u:object_r:mysqld_db_t:s0`

.. 마운트 해제 및 다시 마운트 `/opt/netapp/data/` 상황 활성화를 위한 것입니다.
.. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 로 설정합니다 `mysqld_db_t`:
+
`mount <nfsshare>:/<mountpoint> /opt/netapp/data -o context=system_u:object_r:mysqld_db_t:s0`



. 컨텍스트가 올바르게 설정되었는지 확인합니다.


`ls -dZ /opt/netapp/data/`

샘플 출력:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/
----


== SELinux 컨텍스트 구성 시기 `/opt/netapp` 이(가) 장착된 경우 및 입니다 `/opt/netapp/data/` 또한 별도로 장착됩니다

이 시나리오에서는 먼저 에 대한 컨텍스트를 설정해야 합니다 `/opt/netapp/data/` 이전 섹션에서 설명한 대로 에 대한 올바른 컨텍스트를 설정한 후 `/opt/netapp/data/`상위 디렉토리가 있는지 확인합니다 `/opt/netapp` 에 SELinux 컨텍스트가 설정되어 있지 않습니다 `file_t`.

.단계
. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
`ls -dZ /opt/netapp`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:file_t:s0 /opt/netapp
----
+
이 출력에서 컨텍스트는 입니다 `file_t` 변경해야 합니다. 다음 명령을 실행하면 컨텍스트가 로 설정됩니다 `usr_t`. 컨텍스트를 이외의 값으로 설정할 수 있습니다 `file_t` 보안 요구 사항을 기반으로 합니다.

. 마운트한 방법에 따라 컨텍스트를 설정하려면 다음 단계를 수행하십시오 `/opt/netapp`.
+
.. 다음 명령을 실행하여 컨텍스트를 설정합니다.




[listing]
----
semanage fcontext -a -t usr_t "/opt/netapp"
restorecon -v /opt/netapp
----
. 을(를) 구성한 경우 `/opt/netapp` 인치 `/etc/fstab`을 편집해야 합니다 `/etc/fstab` 파일. 의 경우 `/opt/netapp` 마운트 옵션을 선택하고 MySQL 레이블을 다음과 같이 추가합니다.
+
`context=system_u:object_r:usr_t:s0`

. 마운트 해제한 다음 다시 마운트합니다 `/opt/netapp` 상황 활성화를 위한 것입니다.
. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 설정합니다.
+
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:usr_t:s0`

+
.. 컨텍스트가 올바르게 설정되었는지 확인합니다.
+
`ls -dZ /opt/netapp`

+
샘플 출력입니다





[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:usr_t:s0 /opt/netapp
----


== SELinux 컨텍스트 구성 시기 `/opt/netapp` 이(가) 장착된 경우 및 입니다 `/opt/netapp/data/` 은(는) 별도로 마운트되지 않습니다

을(를) 장착한 경우  `/opt/netapp` 시스템과 SELinux가 로 설정되어 있습니다 `Enforcing`에 대한 SELinux 컨텍스트 유형이 있는지 확인합니다 `/opt/netapp` 가 로 설정되어 있습니다 `mysqld_db_t`데이터베이스 파일 위치에 대한 기본 컨텍스트 요소입니다.

.단계
. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
`ls -dZ /opt/netapp`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp
----
+

NOTE: 이 출력에서 컨텍스트는 입니다 `default_t`. 이 컨텍스트를 로 변경해야 합니다 `mysqld_db_t`.

. 마운트한 방법에 따라 컨텍스트를 설정하려면 다음 단계를 수행하십시오 `/opt/netapp`.
+
.. 다음 명령을 실행하여 컨텍스트를 로 설정합니다 `mysqld_db_t`:
`semanage fcontext -a -t mysqld_db_t "/opt/netapp"
`restorecon -R -v /opt/netapp`
.. 을(를) 구성한 경우 `/opt/netapp` 인치 `/etc/fstab`를 편집합니다 `/etc/fstab` 파일. 의 경우 `/opt/netapp/` 마운트 옵션을 선택하고 MySQL 레이블을 다음과 같이 추가합니다.
`context=system_u:object_r:mysqld_db_t:s0`
.. 마운트 해제한 다음 다시 마운트합니다 `/opt/netapp/` 상황 활성화를 위한 것입니다.
.. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 로 설정합니다 `mysqld_db_t`:
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:mysqld_db_t:s0`


. 컨텍스트가 올바르게 설정되었는지 확인합니다.


`ls -dZ /opt/netapp/`

샘플 출력:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/
----
'''